Real SSR for ads
wp-pwa/wp-pwa pull request #118
Opened 2018-10-16 10:51 UTC by DAreRodz

Closes https://github.com/frontity/frontity/issues/69

2018-10-17 14:30 UTC, orballo requested changes

2018-10-17 14:30 UTC, orballo commented on core/packages/ads/shared/components/Ad/AdSense/index.js
> +import call from 'raw-loader!babel-loader?forceEnv=devClient!./functions/call';
This loader is obsolete. Once https://github.com/frontity/frontity/pull/124 is merged, `dev` should be merged to this branch to fix bugs.

2018-10-17 14:33 UTC, orballo commented on core/packages/ads/shared/components/Ad/DoubleClick/index.js
> +import call from 'raw-loader!babel-loader?forceEnv=devClient!./functions/call';
This loader is also obsolete. https://github.com/frontity/frontity/pull/118/files/2839af4f9caeaa6936375cea3ed816d1e4b1864c#r225954813

2018-10-18 06:29 UTC, luisherranz commented
This is interesting. Let me know how you solve it guys.

2018-10-18 08:40 UTC, DAreRodz commented
@orballo ready to be reviewed again!

2018-10-18 14:03 UTC, orballo approved these changes

2018-10-18 14:03 UTC, merged

2018-10-24 15:20 UTC, frontibotito commented
:tada: This PR is included in version 0.7.2 :tada:

The release is available on [GitHub release](https://github.com/frontity/frontity/releases/tag/v0.7.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: