Create ErrorBoundary and use it in App
wp-pwa/wp-pwa pull request #123
Opened 2018-10-17 11:35 UTC by DAreRodz

Fixes #117

2018-10-22 13:58 UTC, orballo requested changes
ErrorBoundary state should be removed.

2018-10-22 14:13 UTC, DAreRodz commented
Ready to review again

2018-10-22 14:14 UTC, orballo approved these changes

2018-10-22 14:14 UTC, merged

2018-10-24 15:20 UTC, frontibotito commented
:tada: This PR is included in version 0.7.2 :tada:

The release is available on [GitHub release](https://github.com/frontity/frontity/releases/tag/v0.7.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: